spring:
  # 数据库配置
  datasource:
      url: jdbc:mysql://localhost:3306/spring-security-sdk?characterEncoding=utf-8&uesSSL=false
      username: root
      password: zwz520
      driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  security:
    user:
      name: user
      password: 123
      roles: USER
server:
  port: 80
user-default:
  security:
    social:
      filter-process-url: /qqLogin
      qq:
        provider-id: callback.do
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
#    browser:
#      login-page: /demo-login.html
#      register-page: /demo-register.html
#    code:
#      image:
#        length: 6
#        width: 100
#        intercept-url: /user,/user/*